name: Atualizar página com última release

on:
  release:
    types: [published]

jobs:
  build-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deste repositório (páginas)
        uses: actions/checkout@v4

      - name: Baixar asset da release
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.release.tag_name }}
          fileName: "*.apk"
          out-file-path: "downloads"
          tarBall: false
          zipBall: false

      - name: Calcular SHA-256
        id: sha
        run: |
          FILE=$(ls downloads/*.apk | head -n1)
          echo "apk=$FILE" >> $GITHUB_OUTPUT
          echo "sha256=$(sha256sum $FILE | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Gerar index.html
        run: |
          TAG="${{ github.event.release.tag_name }}"
          DATE="$(date +'%d/%m/%Y')"
          APK_NAME="$(basename '${{ steps.sha.outputs.apk }}')"
          APK_URL="https://github.com/${{ github.repository }}/releases/download/${TAG}/${APK_NAME}"

          cat > index.html <<'HTML'
          <!doctype html>
          <html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
          <title>SimulaPRONAF – Downloads</title>
          <style>
          body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;margin:24px;color:#1f2937}
          .card{max-width:720px;margin:auto;padding:24px;border:1px solid #e5e7eb;border-radius:16px;box-shadow:0 4px 14px rgba(0,0,0,.05)}
          h1{margin:0 0 8px}.tag{display:inline-block;padding:2px 10px;border-radius:999px;background:#f59e0b;color:#fff;font-weight:700;font-size:12px;margin-left:8px}
          .muted{color:#6b7280}.btn{display:inline-block;padding:12px 18px;border-radius:10px;text-decoration:none;font-weight:700;border:1px solid #0ea5e9}
          .primary{background:#0ea5e9;color:#fff}.row{display:flex;gap:12px;flex-wrap:wrap;align-items:center}
          .mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,"Liberation Mono",monospace}
          </style></head><body><div class="card">
          <h1>SimulaPRONAF <span class="tag">BETA</span></h1>
          <p class="muted">Baixe o APK oficial para testes. Repositório de código permanece privado.</p>
          <h3>Versão mais recente</h3>
          <p>TAG_PLACEHOLDER – <span class="muted">DATE_PLACEHOLDER</span></p>
          <div class="row">
            <a class="btn primary" href="APK_URL_PLACEHOLDER" download>📦 Baixar APK (TAG_PLACEHOLDER)</a>
            <a class="btn" href="https://github.com/${{ github.repository }}/releases/tag/TAG_PLACEHOLDER">🔎 Ver release</a>
          </div>
          <h3>Checksums (integridade)</h3>
          <pre class="mono">SHA-256: SHA_PLACEHOLDER</pre>
          <h3>Como instalar (Android)</h3>
          <ol><li>Baixe o APK no seu dispositivo.</li><li>Ative “Instalar apps de fontes desconhecidas”.</li><li>Abra o APK e siga as instruções.</li></ol>
          <p class="muted">Contato: woquadros@gmail.com</p>
          </div></body></html>
          HTML

          sed -i "s/TAG_PLACEHOLDER/$TAG/g" index.html
          sed -i "s/DATE_PLACEHOLDER/$DATE/g" index.html
          sed -i "s#APK_URL_PLACEHOLDER#$APK_URL#g" index.html
          sed -i "s/SHA_PLACEHOLDER/${{ steps.sha.outputs.sha256 }}/g" index.html

      - name: Publicar no GitHub Pages (branch gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
